swagger: "2.0"
info:
  title: audio-agent-api
  description: API for the JUCE Audio Agent
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /get-parameters:
    post:
      summary: Takes a text prompt and returns audio parameters.
      operationId: get-parameters
      x-google-backend:
        address: https://us-central1-effect-sequencer.cloudfunctions.net/get_audio_parameters
      # This security definition now points to the name "api_key_name"
      security:
        - api_key_name: []
      responses:
        "200":
          description: A successful response
          schema:
            type: string

# Top-level security definition that links the key to the service
security:
  - api_key_name: []

securityDefinitions:
  # The name here ("api_key_name") must match what's used in the security sections
  api_key_name:
    type: "apiKey"
    name: "x-api-key"
    in: "header"